### ISSUE TITLE
Maven fails to find "org.lucasr.twowayview:core:0.1.1" on Android Studio

### ISSUE THREAD

**Issue by krtkush** [lucasr/twoway-view#105]
On an attempt to import the library through maven, Android Studio throws **"Error:Failed to find: org.lucasr.twowayview:core:0.1.1"**

Android Studio version: (Beta) 0.8.6

Same error is thrown by the snapshot dependencies.

**Comment by MuhammadKorany** [comment]
Error raise on the grid and list attributes like:
Error:(18) No resource identifier found for attribute 'twowayview_layoutManager' in package 'myPackage'

Error:(18) No resource identifier found for attribute 'twowayview_numColumns' in package 'myPackage'

Error:(18) No resource identifier found for attribute 'twowayview_numRows' in package 'myPackage'

How could it get solved?
