### ISSUE TITLE
Is it possiable to make CursorAdapter be set in recycleview, just like ListView?

### ISSUE THREAD

**Issue by machinezhou** [lucasr/twoway-view#118]
I didn't google out a solution till now  to replace listview in my project, because I need to use the cursor linked with the sqlite.

Old way as followed:
listview.setAdapter(cursorAdapter)//in this way, I can get the cursor to deal with data in database

but now, recycleview.setAdapter(recycleview.adapter)// it doesn't recognize the adapter extending BaseAdapter

so anyone can give me a hand?

**Comment by theoklink** [comment]
Two years on an nothing appears to have happened here. Looks like this project is also half finished, just like smoothie
