### ISSUE TITLE
Need gradle tools 21.1.2

### ISSUE THREAD

**Issue by IgorGanapolsky** [lucasr/twoway-view#198]
Hello,
why can't you update Travis CI with gradle build tools 21.1.2? It is currently failing my build. The latest gradle plugin should indeed be <b>21.1.2<b>!

**Comment by skyfishjy** [comment]
@lucasr [[build] Update to latest gradle and android plugin](https://github.com/lucasr/twoway-view/commit/99c4a18fc011ae7d57ebdc9095c04daee7283e39) fix this issue
