### ISSUE TITLE
RecyclerView$LayoutParams cannot be cast to SpannableGridLayoutManager$LayoutParams

### ISSUE THREAD

**Issue by bpillon** [lucasr/twoway-view#202]
Hi,

I'm trying to make a custom display on my grid and for that, I want to use SpannableGridLayoutManager's LayoutParams.

I have something like that :

    public void onBindViewHolder(CategoryViewHolder holder, int position) {
        Category category = mItems.get(position);
        holder.name.setText(category.name);

        final View itemView = holder.itemView;

        final int itemId = position;

        final SpannableGridLayoutManager.LayoutParams lp =
                (SpannableGridLayoutManager.LayoutParams) itemView.getLayoutParams();

        final int span1 = (itemId == 0 || itemId == 3 ? 2 : 1);
        final int span2 = (itemId == 0 ? 2 : (itemId == 3 ? 3 : 1));

        final int colSpan = (true ? span2 : span1);
        final int rowSpan = (true ? span1 : span2);

        if (lp.rowSpan != rowSpan || lp.colSpan != colSpan) {
            lp.rowSpan = rowSpan;
            lp.colSpan = colSpan;
            itemView.setLayoutParams(lp);
        }
    }

And i obtain the following error : 
       java.lang.ClassCastException: android.support.v7.widget.RecyclerView$LayoutParams cannot be cast to org.lucasr.twowayview.widget.SpannableGridLayoutManager$LayoutParams

Do you see any explanation for this error ? Thanks

**Comment by bpillon** [comment]
I replaced my adapter by yours in samples and it's worked... After comparison I don't find any difference but it works.

**Comment by leeheungsoo** [comment]
it's to late....
i show same issue. 

member_list.setLayoutManager(new SpannableGridLayoutManager(getActivity()));

i try add layoutmanger to twowayview, then it's work
