### ISSUE TITLE
Inability to set numcolumns and numrows programmatically

### ISSUE THREAD

**Issue by Deepscorn** [lucasr/twoway-view#220]
The only way to set them now is to set them in xml:
app:twowayview_numColumns="15"
app:twowayview_numRows="25"
Correct me, if I'm wrong

**Comment by gioffy** [comment]
Right now, I'm using this approach to declare the number of columns.
```java
mLayoutManager = new SpannableGridLayoutManager(TwoWayLayoutManager.Orientation.VERTICAL,colsCount,rowsCount);
mRecyclerView.setLayoutManager(mLayoutManager);
```
I don't know your use case so I can't answer a better way.

**Comment by Deepscorn** [comment]
It works! Thank you!
