### ISSUE TITLE
Endless scrolling feature

### ISSUE THREAD

**Issue by pablobaldez** [lucasr/twoway-view#241]
There is anyway to implement the endless scrolling feature, when any listener would load more itens when the user scroll its list to the end?

With linear LinearLayoutManager  I'm used to use the findFirstVisibleItemPosition() method to help me in this implementation, but this method doesn't exists in yours LayoutManager. 

How can i do this now?

**Comment by bemusementpark** [comment]
either in your adapter when you getView the last view, or in your RecyclerView when you've scrolled to/near the bottom.

**Comment by pablobaldez** [comment]
ok but how can i find the first visible position? where is this method or something like this?

**Comment by KoMinkyu** [comment]
I implemented like this.

``` java
if (twoWayView.getLastVisiblePosition() < twoWayView.getAdapter().getItemCount() - 1) {
    // load next page
}
```

**Comment by pablobaldez** [comment]
nice! thank you

**Comment by summers314** [comment]
@KoMinkyu  Another solution is mentioned here. Which one is better?

https://github.com/lucasr/twoway-view/issues/49

**Comment by KoMinkyu** [comment]
@summers314 that solution makes performance issue.
We have to avoid calling `notifyDataSetChanged()` with RecyclerView, specially in `onScrolled()`.
But making `loading` state can help us to create more clear `HTTP requests` when scrolling.
