### ISSUE TITLE
Implement Endless list

### ISSUE THREAD

**Issue by Uname-nikunj** [lucasr/twoway-view#49]
Can you please implement functionality of Endless list with this Twoway- view so for huge data loading its good to use.

Thanks
Nkpatel

**Comment by arashsammak** [comment]
well, how?!! how to implement this in adapter?!

**Comment by arashsammak** [comment]
in found solution 

mRecyclerView.setOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {

```
            visibleItemCount = mRecyclerView.getChildCount();
            totalItemCount = adapter.getItemCount();
            pastVisiblesItems = mRecyclerView.getFirstVisiblePosition();
            adapter.notifyDataSetChanged();

            if (loading) {
                if ((visibleItemCount + pastVisiblesItems) >= totalItemCount) {
                    loading = false;
                    Log.v("...", "Last Item Wow !");

                 // REQUEST LOAD MORE

                    adapter.notifyDataSetChanged();
                }
            }
        }
    });
```

**Comment by summers314** [comment]
@arashsammak  I was gonna implement the above method. Are there any updates to it, or does it work fine?
